# Carga y Preprocesamiento de Datos.
1. Cargar los datos del archivo CSV utilizando NumPy.

In [ ]:
# Primero conectamos con Google Drive (Si esque estamos trabajando en Google Colab).
from google.colab import drive
drive.mount('/content/drive')

In [4]:
# Importamos librerias.
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [7]:
# Importamos nuestro DataFrame.
path = "../data/retail_sales_dataset.csv"
df = pd.read_csv(path)
df

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

2. Realizar un preprocesamiento básico para asegurarte de que los datos estén limpios y listos para su análisis.

In [8]:
# Utilizamos info() para ver si tenemos datos nulos.
df.info()
# Comprobamos que los datos se encuentran completos.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   object
 2   Customer ID       1000 non-null   object
 3   Gender            1000 non-null   object
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   object
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), object(4)
memory usage: 70.4+ KB

In [9]:
df["Total Amount"].describe()

count    1000.000000
mean      456.000000
std       559.997632
min        25.000000
25%        60.000000
50%       135.000000
75%       900.000000
max      2000.000000
Name: Total Amount, dtype: float64

Con el metodo describe() iterando sobre cada columna, observamos que los datos son válidos, no hay precios o edades negativas, todo se ve listo para trabajar.

# Exploración de Datos.
1. Calcula el total de ventas por categoría de producto.

In [11]:
# Agrupamos por Categoría. Obtenemos la columna de Monto Total de cada fila, y sumamos todas las filas por cada Categoría.
total_ventas = df.groupby("Product Category")["Total Amount"].sum()

total_ventas

Product Category
Beauty         143515
Clothing       155580
Electronics    156905
Name: Total Amount, dtype: int64

2. Calcula el promedio de ventas diarias por categoría de producto.

In [12]:
# Obtenemos el promedio de ventas agrupado por Categoría y Fecha.
promedio_ventas_por_cada_fecha = df.groupby(["Product Category", "Date"])["Total Amount"].mean()

# Y en base a eso, agrupamos nuevamente por categoría y obtenemos el promedio diario.
promedio_ventas_diario = promedio_ventas_por_cada_fecha.groupby("Product Category").mean()

promedio_ventas_diario

Product Category
Beauty         453.568627
Clothing       444.132543
Electronics    455.520167
Name: Total Amount, dtype: float64

3. Identifica las categorías de productos con mayores y menores ventas.

In [13]:
# Utilizando los resultados anteriores, podemos obtener el minimo y máximo del total de ventas de cada categoría.
# Ordenamos el total de ventas de forma ascendiente.
total_ventas_ordenado = total_ventas.sort_values(ascending=True)

# El máximo correspondería al último valor, y el mínimo al primer valor.
max_vendido, max_producto = total_ventas_ordenado.iloc[-1], total_ventas_ordenado.index[-1]
min_vendido, min_producto = total_ventas_ordenado.iloc[0], total_ventas_ordenado.index[0]

print(f"El producto con mayores ventas fue {max_producto} con un monto total de ventas de ${max_vendido}.")
print(f"El producto con menores ventas fue {min_producto} con un monto total de ventas de ${min_vendido}.")

El producto con mayores ventas fue Electronics con un monto total de ventas de $156905.
El producto con menores ventas fue Beauty con un monto total de ventas de $143515.

# Manipulación de Datos:
1. Filtra los datos para mostrar solo las ventas de una categoría de producto específica.

In [14]:
# Primero obtenemos las posibles categorías a elegir.
df["Product Category"].unique()

array(['Beauty', 'Clothing', 'Electronics'], dtype=object)

In [15]:
# De estas quiero Clothing. Filtramos los datos para obtener solo sus ventas.
df_clothing = df[df["Product Category"] == "Clothing"]

df_clothing

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
6,7,2023-03-13,CUST007,Male,46,Clothing,2,25,50
9,10,2023-10-07,CUST010,Female,52,Clothing,4,50,200
10,11,2023-02-14,CUST011,Male,23,Clothing,2,50,100
...,...,...,...,...,...,...,...,...,...
986,987,2023-04-29,CUST987,Female,30,Clothing,3,300,900
987,988,2023-05-28,CUST988,Female,63,Clothing,3,25,75
990,991,2023-12-26,CUST991,Female,34,Clothing,2,50,100
994,995,2023-04-30,CUST995,Female,41,Clothing,1,30,30
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50

2. Realiza operaciones de suma, resta, multiplicación y división en los datos para obtener estadísticas adicionales.

In [16]:
# Cantidad total de productos vendidos en la categoría Clothing.
cant_total_vendida = df_clothing["Quantity"].sum()
print(f"En la Categoría Clothing se vendieron en total {cant_total_vendida} productos.")

En la Categoría Clothing se vendieron en total 894 productos.

In [17]:
# La diferencia en precio entre la venta más alta de Clothing y la más baja.
max_venta = df_clothing["Total Amount"].max()
min_venta = df_clothing["Total Amount"].min()
print(f"La mayor venta de Clothing fue de ${max_venta} mientras que la menor fue de ${min_venta}.")
print(f"Por tanto al diferencia entre la venta más alta y la más baja fue de ${max_venta - min_venta}.")

La mayor venta de Clothing fue de $2000 mientras que la menor fue de $25.
Por tanto al diferencia entre la venta más alta y la más baja fue de $1975.

In [18]:
# Obtener el precio promedio de los productos vendidos en clothing.
suma_total_precio_por_producto = df_clothing["Price per Unit"].sum()
cantidad_filas = df_clothing.shape[0]
print(f"En las {cantidad_filas} filas de Clothing, el precio promedio por unidad vendida fue de ${round(suma_total_precio_por_producto/cantidad_filas,2)}.")

En las 351 filas de Clothing, el precio promedio por unidad vendida fue de $174.29.